apiVersion: v1
kind: Service
metadata:
  name: banco-service
  namespace: cervejaria
spec:
  selector:
    app: banco
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  