apiVersion: apps/v1
kind: Deployment
metadata:
  name: cervejaria-acme
  namespace: cervejaria
  labels:
    app: cervejaria-acme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cervejaria-acme
  template:
    metadata:
      name: cervejaria-acme
      labels:
        app: cervejaria-acme
    spec:
      containers:
        - name: cervejaria-acme
          image: leogloriainfnet/acme-cervejaria:latest
          imagePullPolicy: Always
      restartPolicy: Always
      